version: "3"

services:

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - ./data/cache/:/usr/local/cache
    expose:
      - 6379
    restart: on-failure
    
  database:
    container_name: database
    image: mongo:latest
    volumes:
      - ./data/database/:/usr/local/database
    expose:
      - 27017
    restart: on-failure

  users:
    container_name: users
    build:
      context: ./users
    stdin_open: true
    volumes:
      - ./users:/users
      - /users/node_modules
    environment:
      SERVICE_PORT: "${SERVICE_PORT_USERS}"
    depends_on:
      - database
    links:
      - database
    restart: on-failure

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: yolo
      POSTGRES_USER: yolo
      POSTGRES_PASSWORD: yolo
      PGDATA: /data/postgres
    volumes:
      - './data/postgres:/data/postgres'
    ports:
      - "5432:5432"
    restart: unless-stopped


  frontend_app:
    build:
        context: ./frontend
    stdin_open: true
    restart: on-failure
    container_name: frontend
#    depends_on: 
#        - backend
    ports:
        - "80:80"
    volumes:
        - ./frontend:/frontend
        - /frontend/node_modules